authorName: default
experimentName: cifar10
trialConcurrency: 1
maxExecDuration: 2h
maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
localConfig:
  useActiveGpu: true
tuner:
  builtinTunerName: TPE
trial:
  command: python main_nni.py --epochs 50
  codeDir: ../
  gpuNum: 1
